const PRODUCTOS = [
  // ── Línea Botellas 750 ml ($16.000 c/u) ──
  {
    id: 1,
    nombre: 'Vértice Clásica',
    subtitulo: '750 ml · 42% ABV',
    descripcion: 'El corazón de la marca, destilado con botánicos seleccionados que respetan la esencia del London Dry con un toque propio de Pasteur.',
    descripcion_larga: 'Vértice Clásica es nuestro gin insignia. Destilado en alambique de cobre de 20 L siguiendo la tradición London Dry, con un giro único que le dan los quinotos y naranjas amargas cosechados en la plaza de Pasteur. Un gin equilibrado, con presencia del enebro como protagonista y un final cítrico inconfundible. Cada botella es numerada y corresponde a una partida limitada.',
    precio: 16000,
    categoria: 'Botellas 750 ml',
    imagen: '🍸',
    emoji: '🍸',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Alcohol', value: '42% ABV' },
      { label: 'Formato', value: '750 ml' },
      { label: 'Estilo', value: 'London Dry' },
      { label: 'Alambique', value: 'Cobre 20 L' },
      { label: 'Producción', value: 'Small batch' },
    ],
    notas: ['Enebro', 'Quinoto 🌿', 'Naranja amarga 🌿', 'Coriandro', 'Cardamomo', 'Cassia'],
    botanicos: [
      { nombre: 'Enebro', descripcion: 'La base de todo gin. Seleccionado por su perfil resinoso y fresco.', icono: '🌲', local: false },
      { nombre: 'Quinoto', descripcion: 'Aporta una acidez cítrica única, dulce y amarga a la vez.', icono: '🍊', local: true },
      { nombre: 'Naranja amarga', descripcion: 'Notas cítricas profundas que equilibran el enebro.', icono: '🍋', local: true },
      { nombre: 'Coriandro', descripcion: 'Aporta un perfil herbal y ligeramente cítrico.', icono: '🌿', local: false },
      { nombre: 'Cardamomo', descripcion: 'Notas especiadas y ligeramente dulces.', icono: '🌰', local: false },
      { nombre: 'Cassia', descripcion: 'Canela china sutil. Aporta estructura y un toque especiado suave.', icono: '🪵', local: false },
    ],
    proceso_steps: [
      { numero: 1, titulo: 'Selección de botánicos', descripcion: 'Cosechamos quinotos y naranjas de la plaza de Pasteur. El resto de los botánicos los elegimos uno por uno.' },
      { numero: 2, titulo: 'Maceración', descripcion: 'Los botánicos maceran en alcohol neutro de alta calidad durante 24 horas. El tiempo justo para extraer sus aceites esenciales.' },
      { numero: 3, titulo: 'Destilación en cobre', descripcion: 'Alambique de cobre de 20 litros. Controlamos temperatura y caudal gota a gota.' },
      { numero: 4, titulo: 'Embotellado artesanal', descripcion: 'Cada botella se llena, etiqueta y numera a mano. Producimos partidas limitadas.' },
    ],
  },
  {
    id: 2,
    nombre: 'Vértice Macerada',
    subtitulo: '750 ml · 42% ABV',
    descripcion: 'Una versión con carácter, donde los botánicos reposan más tiempo para extraer una mayor profundidad de sabor y aromas intensos.',
    descripcion_larga: 'Vértice Macerada lleva el proceso un paso más allá. Los mismos botánicos de la Clásica, pero con una maceración extendida que extrae una mayor profundidad de sabor y aromas más intensos. El resultado es un gin de personalidad marcada, ideal para quienes buscan una experiencia más compleja en copa. Perfecto en cócteles de autor o en un Gin Tonic con guarniciones especiadas.',
    precio: 16000,
    categoria: 'Botellas 750 ml',
    imagen: '🥃',
    emoji: '🥃',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Alcohol', value: '42% ABV' },
      { label: 'Formato', value: '750 ml' },
      { label: 'Estilo', value: 'London Dry — Maceración extendida' },
      { label: 'Alambique', value: 'Cobre 20 L' },
      { label: 'Maceración', value: '48 horas' },
    ],
    notas: ['Enebro', 'Quinoto 🌿', 'Naranja amarga 🌿', 'Coriandro', 'Cardamomo', 'Cassia', 'Pimienta negra'],
    botanicos: [
      { nombre: 'Enebro', descripcion: 'La base de todo gin. Perfil resinoso intensificado por la maceración.', icono: '🌲', local: false },
      { nombre: 'Quinoto', descripcion: 'Aporta una acidez cítrica única, más profunda con la maceración extendida.', icono: '🍊', local: true },
      { nombre: 'Naranja amarga', descripcion: 'Notas cítricas profundas que se potencian con el reposo.', icono: '🍋', local: true },
      { nombre: 'Coriandro', descripcion: 'Perfil herbal y ligeramente cítrico.', icono: '🌿', local: false },
      { nombre: 'Cardamomo', descripcion: 'Notas especiadas que ganan intensidad.', icono: '🌰', local: false },
      { nombre: 'Cassia', descripcion: 'Canela china. Estructura y calidez.', icono: '🪵', local: false },
      { nombre: 'Pimienta negra', descripcion: 'Un toque picante sutil que redondea el perfil.', icono: '🌶️', local: false },
    ],
    proceso_steps: [
      { numero: 1, titulo: 'Selección de botánicos', descripcion: 'Los mismos botánicos de la Clásica, seleccionados uno por uno.' },
      { numero: 2, titulo: 'Maceración extendida', descripcion: '48 horas de reposo en alcohol neutro. El doble de tiempo para extraer al máximo los aceites esenciales y compuestos aromáticos.' },
      { numero: 3, titulo: 'Destilación lenta', descripcion: 'Alambique de cobre de 20 litros. Destilación más lenta para capturar los compuestos más pesados y complejos.' },
      { numero: 4, titulo: 'Embotellado artesanal', descripcion: 'Cada botella se llena, etiqueta y numera a mano.' },
    ],
  },
  {
    id: 3,
    nombre: 'Vértice Limón',
    subtitulo: '750 ml · 42% ABV',
    descripcion: 'Inspirada en la frescura cítrica, ideal para quienes buscan un Gin Tonic más ligero y refrescante.',
    descripcion_larga: 'Vértice Limón nace de la idea de un gin cítrico y refrescante sin perder la esencia artesanal. Botánicos cuidadosamente seleccionados con un protagonismo especial del limón, la naranja y el pomelo. El resultado es un gin vibrante, perfecto para tardes de calor, para quienes se inician en el mundo del gin, o para quienes buscan un trago más ligero sin sacrificar calidad.',
    precio: 16000,
    categoria: 'Botellas 750 ml',
    imagen: '🍋',
    emoji: '🍋',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Alcohol', value: '42% ABV' },
      { label: 'Formato', value: '750 ml' },
      { label: 'Estilo', value: 'Contemporary Citrus Gin' },
      { label: 'Alambique', value: 'Cobre 20 L' },
      { label: 'Perfil', value: 'Cítrico y refrescante' },
    ],
    notas: ['Enebro', 'Limón 🌿', 'Naranja 🌿', 'Pomelo 🌿', 'Menta', 'Jengibre'],
    botanicos: [
      { nombre: 'Enebro', descripcion: 'La base de todo gin. En esta versión se suaviza para dejar lugar a los cítricos.', icono: '🌲', local: false },
      { nombre: 'Limón', descripcion: 'Cosechado en Pasteur. Frescura y acidez natural.', icono: '🍋', local: true },
      { nombre: 'Naranja', descripcion: 'Dulzor cítrico que equilibra la acidez del limón.', icono: '🍊', local: true },
      { nombre: 'Pomelo', descripcion: 'Amargor cítrico sutil que aporta complejidad.', icono: '🍈', local: true },
      { nombre: 'Menta', descripcion: 'Frescura herbal que realza el perfil refrescante.', icono: '🌿', local: false },
      { nombre: 'Jengibre', descripcion: 'Un toque picante y aromático que despierta el paladar.', icono: '🫚', local: false },
    ],
    proceso_steps: [
      { numero: 1, titulo: 'Selección de botánicos', descripcion: 'Cítricos frescos de Pasteur combinados con botánicos clásicos.' },
      { numero: 2, titulo: 'Maceración', descripcion: '24 horas en alcohol neutro. Las cáscaras de cítricos aportan sus aceites esenciales.' },
      { numero: 3, titulo: 'Destilación en cobre', descripcion: 'Alambique de cobre de 20 litros. Destilación cuidadosa para preservar los aromas cítricos volátiles.' },
      { numero: 4, titulo: 'Embotellado artesanal', descripcion: 'Cada botella se llena, etiqueta y numera a mano.' },
    ],
  },
  // ── Línea Especial ──
  {
    id: 4,
    nombre: 'Puente Aperitivo Cítrico',
    subtitulo: '500 ml · 18% ABV',
    descripcion: 'Una nueva propuesta, vibrante y refrescante, diseñada para ser el "puente" perfecto en tus aperitivos.',
    descripcion_larga: 'Puente es nuestro aperitivo cítrico. Menor graduación alcohólica que nuestro gin, pensado para esos momentos donde querés algo más ligero pero con carácter. Ideal con soda, hielo y una rodaja de naranja. También funciona como base para cócteles de aperitivo.',
    precio: 10000,
    categoria: 'Línea Especial',
    imagen: '🍹',
    emoji: '🍹',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Alcohol', value: '18% ABV' },
      { label: 'Formato', value: '500 ml' },
      { label: 'Perfil', value: 'Cítrico — Aperitivo' },
      { label: 'Maridaje', value: 'Soda, hielo, naranja' },
    ],
  },
  {
    id: 5,
    nombre: 'Petaca "Pasteur Ruta 68"',
    subtitulo: '200 ml · 42% ABV',
    descripcion: 'La experiencia Vértice en formato compacto, ideal para llevar o regalar.',
    descripcion_larga: 'Nuestra Petaca "Pasteur Ruta 68" es el formato portable de Vértice. 200 ml del mismo gin artesanal, en un envase práctico y resistente. Llevala a un picnic, a una juntada, o regalala como detalle. La Ruta 68 es la ruta que pasa por Pasteur — un homenaje a nuestro pueblo.',
    precio: 6000,
    categoria: 'Línea Especial',
    imagen: '🧴',
    emoji: '🧴',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Alcohol', value: '42% ABV' },
      { label: 'Formato', value: '200 ml' },
      { label: 'Estilo', value: 'London Dry' },
    ],
  },
  // ── Accesorios y Mixes ──
  {
    id: 6,
    nombre: 'Caja Mix Botánicos',
    subtitulo: 'Selección de aromas',
    descripcion: 'El complemento indispensable para realzar los aromas de tu gin.',
    descripcion_larga: 'Una selección de botánicos adicionales para personalizar tu gin. Incluye enebro extra, pimienta rosa, lavanda, y más. Agregalos a tu copa para potenciar o modificar el perfil aromático de tu trago.',
    precio: 2000,
    categoria: 'Accesorios',
    imagen: '🌿',
    emoji: '🌿',
    stock: -1,
    activo: true,
  },
  {
    id: 7,
    nombre: 'Caja Mix Botánicos XL',
    subtitulo: 'Selección de aromas — formato grande',
    descripcion: 'El complemento indispensable para realzar los aromas de tu gin.',
    descripcion_larga: 'La versión XL de nuestra Caja Mix Botánicos. Más cantidad y más variedad de botánicos para los más experimentados. Ideal para bares o regalar a un entusiasta del gin.',
    precio: 6000,
    categoria: 'Accesorios',
    imagen: '🌱',
    emoji: '🌱',
    stock: -1,
    activo: true,
  },
  {
    id: 8,
    nombre: 'Copa Gin Vértice',
    subtitulo: 'Cristalería seleccionada',
    descripcion: 'Copa individual diseñada para disfrutar de cada trago.',
    descripcion_larga: 'Copa de cata serigrafiada con el logo de Vértice. Diseñada para realzar los aromas del gin, con la forma ideal para Gin Tonic o cócteles. Presentación individual.',
    precio: 9000,
    categoria: 'Accesorios',
    imagen: '🥂',
    emoji: '🥂',
    stock: -1,
    activo: true,
  },
  {
    id: 9,
    nombre: 'Vaso Gin Vértice',
    subtitulo: 'Cristalería seleccionada',
    descripcion: 'Vaso individual diseñado para disfrutar de cada trago.',
    descripcion_larga: 'Vaso serigrafiado con el logo de Vértice. Estilo old fashioned, perfecto para aperitivos, cócteles en las rocas o disfrutar de Puente con soda.',
    precio: 5000,
    categoria: 'Accesorios',
    imagen: '🥤',
    emoji: '🥤',
    stock: -1,
    activo: true,
  },
  // ── Combos y Packs ──
  {
    id: 10,
    nombre: 'Copa o Vaso en combo',
    subtitulo: 'Ahorrá con el combo',
    descripcion: 'Opción ideal para completar tu equipo de coctelería.',
    descripcion_larga: 'Elegí entre copa o vaso a un precio especial cuando los comprás solos. El combo perfecto para armar tu kit de gin.',
    precio: 7000,
    precio_alternativo: { label: 'Vaso', value: 3500 },
    categoria: 'Combos',
    imagen: '🎯',
    emoji: '🎯',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Copa', value: '$7.000' },
      { label: 'Vaso', value: '$3.500' },
    ],
  },
  {
    id: 11,
    nombre: 'Combo 2 Petacas',
    subtitulo: 'Ruta 68 x2',
    descripcion: 'El dúo perfecto para compartir.',
    descripcion_larga: 'Dos Petacas "Pasteur Ruta 68" en un combo con descuento. Ideal para regalar en pareja, para llevar a dos eventos distintos, o para tener una de respuesto.',
    precio: 10000,
    categoria: 'Combos',
    imagen: '🧴🧴',
    emoji: '🧴🧴',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Contenido', value: '2 × 200 ml' },
      { label: 'Alcohol', value: '42% ABV' },
      { label: 'Ahorro', value: '~17% vs. unidad' },
    ],
  },
  {
    id: 12,
    nombre: 'Pack 6 Botellas 750 ml',
    subtitulo: 'Seleccioná tus variantes',
    descripcion: 'La opción mayorista para eventos o abastecer tu bar personal.',
    descripcion_larga: 'Seis botellas de 750 ml. Elegí las variantes que quieras (Clásica, Macerada, Limón) y armá tu pack personalizado. Incluye envío sin cargo a todo el país.',
    precio: 81000,
    categoria: 'Combos',
    imagen: '📦',
    emoji: '📦',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Contenido', value: '6 × 750 ml' },
      { label: 'Ahorro', value: '~16% vs. unidad' },
    ],
  },
  {
    id: 13,
    nombre: 'Caja Vértice Nº1',
    subtitulo: '1 botella + 1 copa + mix botánicos',
    descripcion: 'Presentación lista para regalar. Incluye botella Clásica, copa Vértice y Mix Botánicos.',
    descripcion_larga: 'La Caja Vértice Nº1 es el regalo perfecto. Incluye una botella de Vértice Clásica 750 ml, una copa de cata serigrafiada y una Caja Mix Botánicos. Todo en una presentación elegante lista para regalar.',
    precio: 27000,
    categoria: 'Combos',
    imagen: '🎁',
    emoji: '🎁',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Incluye', value: '1 botella Clásica 750 ml' },
      { label: 'Incluye', value: '1 Copa Vértice' },
      { label: 'Incluye', value: '1 Mix Botánicos' },
    ],
  },
  {
    id: 14,
    nombre: 'Caja Vértice Nº2',
    subtitulo: '2 botellas + 2 copas + mix botánicos XL',
    descripcion: 'Presentación lista para regalar. Dos botellas, dos copas y Mix Botánicos XL.',
    descripcion_larga: 'La Caja Vértice Nº2 es ideal para parejas o para compartir. Incluye dos botellas de Vértice (Clásica y Macerada), dos copas de cata serigrafiadas y una Caja Mix Botánicos XL.',
    precio: 31000,
    categoria: 'Combos',
    imagen: '🎁',
    emoji: '🎁',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Incluye', value: '1 Clásica + 1 Macerada 750 ml' },
      { label: 'Incluye', value: '2 Copas Vértice' },
      { label: 'Incluye', value: '1 Mix Botánicos XL' },
    ],
  },
  {
    id: 15,
    nombre: 'Caja Vértice Nº3',
    subtitulo: '3 botellas + 2 copas + mix botánicos XL',
    descripcion: 'Presentación completa. Las tres variantes de Vértice más accesorios.',
    descripcion_larga: 'La Caja Vértice Nº3 es la experiencia completa. Incluye las tres variantes de Vértice (Clásica, Macerada y Limón), dos copas de cata serigrafiadas y una Caja Mix Botánicos XL. Para los que quieren probarlo todo.',
    precio: 34000,
    categoria: 'Combos',
    imagen: '🎁',
    emoji: '🎁',
    stock: -1,
    activo: true,
    especificaciones: [
      { label: 'Incluye', value: 'Clásica + Macerada + Limón 750 ml' },
      { label: 'Incluye', value: '2 Copas Vértice' },
      { label: 'Incluye', value: '1 Mix Botánicos XL' },
    ],
  },
];

function obtenerProductos() {
  try {
    const overrides = JSON.parse(localStorage.getItem('vertice-productos') || '[]');
    if (!overrides || overrides.length === 0) return PRODUCTOS;
    return PRODUCTOS.map(p => {
      const o = overrides.find(x => x.id === p.id);
      return o ? { ...p, ...o } : p;
    }).concat(overrides.filter(o => !PRODUCTOS.some(p => p.id === o.id)));
  } catch (e) {
    return PRODUCTOS;
  }
}

function guardarProductos(lista) {
  const data = lista.map(p => ({
    id: p.id, nombre: p.nombre, subtitulo: p.subtitulo,
    descripcion: p.descripcion, descripcion_larga: p.descripcion_larga,
    precio: p.precio, precio_alternativo: p.precio_alternativo,
    categoria: p.categoria,
    imagen: p.imagen, emoji: p.emoji,
    stock: p.stock, activo: p.activo,
    especificaciones: p.especificaciones,
    notas: p.notas,
    botanicos: p.botanicos, proceso_steps: p.proceso_steps,
  }));
  localStorage.setItem('vertice-productos', JSON.stringify(data));
}

function formatearPrecio(n) {
  return '$' + Number(n).toLocaleString('es-AR');
}
